/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "<region>",
    "aws_appsync_graphqlEndpoint": "<appsync-endpoint>",
    "aws_appsync_region": "<region>",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "<api-key>"
};


export default awsmobile;
